version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres
    dns:
      - 8.8.8.8

  postgres: 
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_DEVELOPMENT_USER
      - POSTGRES_PASSWORD=$POSTGRES_DEVELOPMENT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DEVELOPMENT_DB
      - PGDATA=$PGDATA
    ports:
      - target: $DB_PORT_CONTAINER
        published: $DB_PORT_HOST_DEVELOPMENT
        protocol: tcp
        mode: host
    command:
      -p $DB_PORT_CONTAINER
    volumes:
      - postgres-data:$PGDATA


volumes:
  postgres-data:
